name: build

on:
  push:
    paths-ignore:
      - '**.md'
    
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
         git clone -b "${GITHUB_REF#refs/heads/}" https://github.com/ryuichiueda/value_iteration.git
         cd value_iteration/test/docker
         sed -i "s;clone;clone -b ${GITHUB_REF#refs/heads/};" Dockerfile
         docker build -t test .
#      - name: Reset and navigation test on Gazebo
#        run: |
#         docker run test /bin/bash -c 'source ~/.bashrc && /catkin_ws/src/emcl/test/test.bash'


